from tkinter import *

def ask():
    frame1 = Frame(root, width=500, height=500)
    frame1.pack()
    theLabel = Label( frame1, text="Choose Context:" )
    theLabel.pack()
    Morning = Button(frame1, text="Morning")
    Morning.pack(side=LEFT)
    Afternoon = Button( frame1, text="Afertnoon" )
    Afternoon.pack(side=LEFT)
    Night = Button( frame1, text="Night" )
    Night.pack(side=LEFT)
    Evening = Button( frame1, text="Evening" )
    Evening.pack( side=LEFT )

    frame2 = Frame( root, width=500, height=500 )
    frame2.pack()
    Winter = Button( frame2, text="Winter" )
    Winter.pack( side=LEFT )
    Spring = Button( frame2, text="Spring" )
    Spring.pack( side=LEFT )
    Summer = Button( frame2, text="Summer" )
    Summer.pack( side=LEFT )
    Fall = Button( frame2, text="Fall" )
    Fall.pack( side=LEFT )

    frame3 = Frame( root, width=500, height=500 )
    frame3.pack()
    Weekday = Button( frame3, text="Weekday" )
    Weekday.pack( side=LEFT )
    Weekend = Button( frame3, text="Weekend" )
    Weekend.pack( side=LEFT )
    Holiday = Button( frame3, text="Holiday" )
    Holiday.pack( side=LEFT )

def getContext():
	print("make later")

root = Tk()

theLabel = Label(root, text="Amadeus")
theLabel.pack()
canvas1 = Canvas( root, width=500, height=50 )
canvas1.pack()
frame = Frame( root, width=500, height=500 )
frame.pack()
canvas2 = Canvas( root, width=500, height=50)
canvas2.pack()
theLabel = Label( frame, text="Choose the Kind of Context:" )
theLabel.pack(side=LEFT)
status = Label( root, text="Choosing Context", bd=1, relief=SUNKEN, anchor=W )
status.pack( side=BOTTOM, fill=X )
frame2 = Frame( root, width=500, height=500 )
frame2.pack(side=BOTTOM)
Button1 = Button(frame, text= "ask", command= ask())
Button1.pack(side=LEFT)
Button2 = Button(frame, text= "get", command= getContext())
Button2.pack(side=LEFT)
canvas3 = Canvas( root, width=500, height=50 )
canvas3.pack()
Button3= Button(frame2, text="recommendation" )
Button3.pack(side=LEFT)
quitButton = Button(frame2, text="Quit", command=frame.quit)
quitButton.pack(side=LEFT)

# mantem a janela aberta
root.mainloop()
